/* 
	상수 초기화 
*/
NURTURE_MODE_MIND := 0
NURTURE_MODE_GOLD := 1

DIFFICULTY_MODE_FIRST := 0
DIFFICULTY_MODE_SECOND := 1
DIFFICULTY_MODE_THIRD := 2

GATHER_MODE_PHYSICS := 0
GATHER_MODE_SPIRIT := 1
GATHER_MODE_BRONZE := 2